const crypto=require("crypto");
const bcrypt=require("bcryptjs");
const { findActiveAdminByEmail }=require("../repositories/adminRepository");
const { findApprovedMemberByEmail }=require("../repositories/memberRepository");
const { createResetToken,findValidResetToken,consumeResetToken }=require("../repositories/passwordResetRepository");
const { sendEmail }=require("../services/emailService");
const { getAppConfig }=require("../config/env");
const { buildPage }=require("../utils/page");
const neutral="If an account exists for this email, password reset instructions have been sent.";
const hash=t=>crypto.createHash("sha256").update(t).digest("hex");
function renderForgot(req,res){res.render("auth/forgot-password",{page:buildPage("/forgot-password","Forgot Password")});}
async function requestReset(req,res){const email=String(req.body.email||"").trim().toLowerCase(); const admin=await findActiveAdminByEmail(email); const member=admin?null:await findApprovedMemberByEmail(email); const user=admin||member; if(user){const raw=crypto.randomBytes(32).toString("hex"); const accountType=admin?"admin":"member"; const expiresAt=new Date(Date.now()+30*60*1000); await createResetToken({accountType,accountId:user.id,tokenHash:hash(raw),expiresAt}); const origin=(getAppConfig().siteUrl||`${req.protocol}://${req.get("host")}`).replace(/\/$/,""); const url=`${origin}/reset-password/${raw}`; try{await sendEmail({to:user.email,subject:"Reset your PEA Jabalpur password",text:`Use this link within 30 minutes to reset your password: ${url}\nIf you did not request this, ignore this email.`,html:`<p>Use the link below within 30 minutes to reset your password.</p><p><a href="${url}">Reset password</a></p><p>If you did not request this, ignore this email.</p>`});}catch(e){console.error("Password reset email failed:",e.message);}} res.render("auth/forgot-password",{page:buildPage("/forgot-password","Forgot Password"),successMessage:neutral});}
async function renderReset(req,res){const valid=await findValidResetToken(hash(req.params.token));res.status(valid?200:400).render("auth/reset-password",{page:buildPage("/reset-password","Reset Password"),token:req.params.token,invalid:!valid});}
async function resetPassword(req,res){const token=req.params.token; const record=await findValidResetToken(hash(token)); const password=String(req.body.password||""); if(!record)return res.status(400).render("auth/reset-password",{page:buildPage("/reset-password","Reset Password"),token,invalid:true}); if(password.length<8||password!==req.body.confirm_password)return res.status(400).render("auth/reset-password",{page:buildPage("/reset-password","Reset Password"),token,invalid:false,errorMessage:"Passwords must match and contain at least 8 characters."}); await consumeResetToken(record,await bcrypt.hash(password,12)); req.session.flash={type:"success",message:"Password reset successfully. You can now sign in."}; res.redirect("/auth/login");}
module.exports={renderForgot,requestReset,renderReset,resetPassword};
